######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 29 13:42:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
LIBS += -lrt
